server:
  port: 8080

spring:
  application:
    name: main
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:""}
    url: ${SPRING_DATASOURCE_URL:""}
    username: ${SPRING_DATASOURCE_USERNAME:""}
    password: ${SPRING_DATASOURCE_PASSWORD:""}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:""}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:""}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:""}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
  jwt:
    secret: ${SPRING_JWT_SECRET:""}

app:
  cors:
    enabled: ${APP_CORS_ENABLED:""}
  jwt:
    access-token:
      expiration: ${APP_JWT_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token:
      expiration: ${APP_JWT_REFRESH_TOKEN_EXPIRATION:2592000000}
